site_name: 'api-1'
site_description: 'Main documentation for the api-1'
repo_url: https://github.com/iagouvea/api-1
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - Getting started: 'docs/index.md'