deployment:
  name: api-1
  replicas: 1
  repository: iagouvea/api-1
  tag: "9e6acc9"


service:
  name: api-1-svc
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  name: api-1-ingress
  className: "nginx"
  host: api-1.dev.local
